Repository CSCI-GA-2820-SP23-001/customers, pull requests merged in 2023-03, with the labels that each got.

#10 adding customer model and tests
  service/__init__.py
  service/common/model_constants.py
  service/models.py
  service/routes.py
  tests/__init__.py
  tests/factories.py
  tests/test_models.py
Labels: technical debt

#17 fixing repo to restore passing state and unblock
  service/__init__.py
  service/common/constants.py
  service/common/model_constants.py
  service/common/strings.py
  service/models.py
  service/routes.py
  tests/factories.py
  tests/test_routes.py
Labels: bug

#19 initial version of list-customers
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#20 Update customer
  .vscode/launch.json
  service/common/strings.py
  service/models.py
  service/routes.py
  tests/__init__.py
  tests/factories.py
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement, technical debt

#21 Added service and tests for customers not found
  service/models.py
  tests/test_models.py
Labels: technical debt
